- name: Play level vars
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Vars from files
  hosts: localhost
  vars_files:
    - demo-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Vars from tasks
  hosts: localhost
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}
      vars:
        URL: tasks.example.com

- name: Vars from Inventory
  hosts: localhost
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Facts
  hosts: localhost
  tasks:
    - name: Print Hostname
      ansible.builtin.debug:
        msg: Host Name = {{ansible_hostname}}, Memory = {{ ansible_memory_mb.real.free }}
    - name: Print FQDN
      ansible.builtin.debug:
        msg: "{{ ansible_fqdn }}"
        # if any value starts with a variable then we need to quote it, Either single or double

