- name: Demo on loops
  hosts: localhost
  tasks:
    - name: Loop Example
      debug:
        msg: Fruit =  {{item}}
      loop:
        - apple
        - banana
    - name: Loop Example with Maps
      debug:
        msg: Fruit Name =  {{item.name}}, Quantity = {{item.quantity}}
      loop:
        - {name: apple, quantity: 10}
        - {name: banana, quantity: 30}
      